-- ============================================
-- PHASE 1: CREATE NEW TABLES
-- Duration: 30 minutes | Risk: ZERO
-- ============================================

USE hr_system;

-- 1. ROLES & PERMISSIONS
CREATE TABLE IF NOT EXISTS roles (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  description TEXT,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS permissions (
  id VARCHAR(191) PRIMARY KEY,
  module VARCHAR(50) NOT NULL,
  action VARCHAR(50) NOT NULL,
  description TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_module_action (module, action),
  INDEX idx_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS role_permissions (
  id VARCHAR(191) PRIMARY KEY,
  roleId VARCHAR(191) NOT NULL,
  permissionId VARCHAR(191) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_role_permission (roleId, permissionId),
  INDEX idx_roleId (roleId),
  INDEX idx_permissionId (permissionId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. DEPARTMENTS & DESIGNATIONS
CREATE TABLE IF NOT EXISTS departments (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(100) UNIQUE NOT NULL,
  code VARCHAR(20) UNIQUE NOT NULL,
  description TEXT,
  parentId VARCHAR(191),
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_parentId (parentId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS designations (
  id VARCHAR(191) PRIMARY KEY,
  title VARCHAR(100) UNIQUE NOT NULL,
  level INT NOT NULL,
  description TEXT,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. LEAVE TYPES & BALANCES
CREATE TABLE IF NOT EXISTS leave_types (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  code VARCHAR(20) UNIQUE NOT NULL,
  defaultBalance INT NOT NULL,
  isPaid BOOLEAN DEFAULT TRUE,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leave_approvals (
  id VARCHAR(191) PRIMARY KEY,
  leaveId VARCHAR(191) NOT NULL,
  approverId VARCHAR(191) NOT NULL,
  level INT NOT NULL,
  status ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
  comments TEXT,
  approvedAt DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_leaveId (leaveId),
  INDEX idx_approverId (approverId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leave_balances (
  id VARCHAR(191) PRIMARY KEY,
  employeeId VARCHAR(191) NOT NULL,
  leaveTypeId VARCHAR(191) NOT NULL,
  year INT NOT NULL,
  allocated INT NOT NULL,
  used INT DEFAULT 0,
  available INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_emp_type_year (employeeId, leaveTypeId, year),
  INDEX idx_employeeId (employeeId),
  INDEX idx_leaveTypeId (leaveTypeId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. DOCUMENTS & HOLIDAYS
CREATE TABLE IF NOT EXISTS employee_documents (
  id VARCHAR(191) PRIMARY KEY,
  employeeId VARCHAR(191) NOT NULL,
  documentType VARCHAR(50) NOT NULL,
  fileName VARCHAR(255) NOT NULL,
  filePath VARCHAR(500) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_employeeId (employeeId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS holidays (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  date DATE NOT NULL,
  type ENUM('PUBLIC', 'OPTIONAL') DEFAULT 'PUBLIC',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. PASSWORD RESETS
CREATE TABLE IF NOT EXISTS password_resets (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  token VARCHAR(255) UNIQUE NOT NULL,
  expiresAt DATETIME NOT NULL,
  isUsed BOOLEAN DEFAULT FALSE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_userId (userId),
  INDEX idx_token (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'Phase 1 Complete!' AS Status;
